workflows:
  ios-build:
    name: Build iOS

    environment:
      flutter: stable

    working_directory: ccb_app   # 👈 QUAN TRỌNG

    scripts:
      - flutter clean
      - flutter pub get
      - flutter build ios --release

    artifacts:
      - build/ios/ipa/*.ipa
