workflows:
  ios-build:
    name: Build iOS

    environment:
      flutter: stable

    scripts:
      - name: Get dependencies
        script: |
          cd ccb_app
          flutter clean
          flutter pub get

      - name: Build iOS
        script: |
          cd ccb_app
          flutter build ios --release

    artifacts:
      - ccb_app/build/ios/ipa/*.ipa
